// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_no_repeat_ngram`, `argmax`, `beam_search`, `first_existing`, `greedy_decode`, `load_inner`, `log_softmax_inplace`, `normalized_score`, `path_string`, `top_k_indices`, `translate_inner`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Beam`, `TranslatorInner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MarianTranslator>>
abstract class MarianTranslator implements RustOpaqueInterface {
  Future<bool> isReady();

  /// Load from explicit file paths.
  static Future<MarianTranslator> load({
    required String modelPath,
    required String configPath,
    required String tokenizerEncPath,
    required String tokenizerDecPath,
  }) => RustLib.instance.api.crateApiMarianMarianTranslatorLoad(
    modelPath: modelPath,
    configPath: configPath,
    tokenizerEncPath: tokenizerEncPath,
    tokenizerDecPath: tokenizerDecPath,
  );

  /// Load from a Helsinki-style model folder.
  static Future<MarianTranslator> loadFromDir({required String modelDir}) =>
      RustLib.instance.api.crateApiMarianMarianTranslatorLoadFromDir(
        modelDir: modelDir,
      );

  /// Translate `text` with optional decode config (defaults to street-mode).
  Future<String> translate({required String text, TranslationConfig? config});
}

/// Decode hyperparameters matching Malinali street-mode / HuggingFace Marian defaults.
class TranslationConfig {
  final int numBeams;
  final int maxNewTokens;
  final double lengthPenalty;
  final int noRepeatNgramSize;

  const TranslationConfig({
    required this.numBeams,
    required this.maxNewTokens,
    required this.lengthPenalty,
    required this.noRepeatNgramSize,
  });

  static Future<TranslationConfig> default_() =>
      RustLib.instance.api.crateApiMarianTranslationConfigDefault();

  @override
  int get hashCode =>
      numBeams.hashCode ^
      maxNewTokens.hashCode ^
      lengthPenalty.hashCode ^
      noRepeatNgramSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranslationConfig &&
          runtimeType == other.runtimeType &&
          numBeams == other.numBeams &&
          maxNewTokens == other.maxNewTokens &&
          lengthPenalty == other.lengthPenalty &&
          noRepeatNgramSize == other.noRepeatNgramSize;
}
